# Site settings
title: Sample project - Github gh-pages
#email: all@domain.com
description: This is a sample description used for our sample project documentation.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: ""
#github_username:  ""

# Build settings
markdown: kramdown
